### ISSUE TITLE
update README file

### ISSUE THREAD

**Issue by srbcheema1** [srbcheema1/snakeGame#1]
readme file is to be updated .
you may add decoration , stickers , labels , screenshots 
any kind of contributions is accepted

**Comment by AimunKhan** [comment]
I can help with that

**Comment by srbcheema1** [comment]
sure @AimunKhan 
go for it :smile:

**Comment by dhruvsisd** [comment]
May I help you?

**Comment by srbcheema1** [comment]
sure @dhruvsisd

**Comment by dhruvsisd** [comment]
check it

**Comment by srbcheema1** [comment]
merged @dhruvsisd 
never forget to mention PR number in the comment when you are talking about some PR
